name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y bash curl rlwrap openjdk-11-jdk
        curl -O https://download.clojure.org/install/linux-install-1.10.3.855.sh
        sudo chmod +x linux-install-1.10.3.855.sh
        sudo ./linux-install-1.10.3.855.sh
        export DATASTORE_PROJECT_ID=amplified-bee-313606
        clj -P
    - name: Run tests
      run: ./bin/kaocha unit
